import { useRef, useState } from "react";
import TripForm from "./components/TripForm.jsx";
import Itinerary from "./components/Itinerary.jsx";
import { LoadingPanel, ErrorPanel, EmptyPanel } from "./components/StatePanels.jsx";
import { planTrip } from "./api/client.js";
import { isRenderableItinerary } from "./utils/validateItinerary.js";
import { saveSession, loadSession, clearSession } from "./utils/storage.js";

// status: "empty" | "loading" | "error" | "success"

// Restore a previously saved trip on first render, if there is one and it's
// still shaped correctly (schema could've changed since it was saved).
function getInitialState() {
  const saved = loadSession();
  if (saved && isRenderableItinerary(saved.itinerary)) {
    return { status: "success", itinerary: saved.itinerary, lastPrompt: saved.prompt };
  }
  return { status: "empty", itinerary: null, lastPrompt: "" };
}

export default function App() {
  const initial = useRef(getInitialState()).current;
  const [status, setStatus] = useState(initial.status);
  const [itinerary, setItinerary] = useState(initial.itinerary);
  const [error, setError] = useState(null);
  const [lastPrompt, setLastPrompt] = useState(initial.lastPrompt);
  const [justRestored, setJustRestored] = useState(initial.status === "success");

  // Tracks the in-flight request so a second submission can cancel the
  // first. This is what stops a slow, stale response from overwriting a
  // newer one: whichever request's AbortController fires "abort" simply
  // never gets to call setState, because its `signal.aborted` check runs
  // first and it throws before reaching the setItinerary call below.
  const controllerRef = useRef(null);

  const runPlan = async (prompt) => {
    controllerRef.current?.abort();
    const controller = new AbortController();
    controllerRef.current = controller;

    setStatus("loading");
    setError(null);
    setLastPrompt(prompt);

    try {
      const result = await planTrip(prompt, controller.signal);

      // Guard against this response arriving after a newer request already
      // took over (belt-and-suspenders alongside the abort above).
      if (controllerRef.current !== controller) return;

      if (!isRenderableItinerary(result)) {
        setStatus("error");
        setError({ message: "The plan came back in a shape this UI can't render." });
        return;
      }

      setItinerary(result);
      setStatus("success");
      setJustRestored(false);
      saveSession({ prompt, itinerary: result });
    } catch (err) {
      if (controllerRef.current !== controller) return; // superseded, ignore
      if (err.cancelled) return; // user fired another request; that one owns the UI now

      setStatus("error");
      setError({ message: err.message || "Something went wrong.", details: err.details });
    }
  };

  const handleReset = () => {
    controllerRef.current?.abort();
    setStatus("empty");
    setItinerary(null);
    setError(null);
    setJustRestored(false);
    clearSession();
  };

  // Edits (reorder / remove a stop) should survive a refresh too, so every
  // change re-saves against the prompt that produced the original plan.
  const handleItineraryChange = (updated) => {
    setItinerary(updated);
    saveSession({ prompt: lastPrompt, itinerary: updated });
  };

  return (
    <div className="app-shell">
      <header className="app-header">
        <span className="app-mark">Waypoint</span>
      </header>
      <h1 className="app-title">Tell me about the trip.</h1>
      <p className="app-subtitle">
        Describe where you're going and what you're into — I'll lay out a day-by-day
        route you can expand, reorder, and trim down to what you actually want.
      </p>

      <TripForm onSubmit={runPlan} isLoading={status === "loading"} />

      {status === "loading" && <LoadingPanel />}

      {status === "error" && (
        <ErrorPanel
          message={error?.message}
          details={error?.details}
          onRetry={() => runPlan(lastPrompt)}
        />
      )}

      {status === "empty" && <EmptyPanel />}

      {status === "success" && itinerary && (
        <>
          {justRestored && (
            <p className="restored-note">
              Restored your last plan from this browser.{" "}
              <button type="button" className="restored-dismiss" onClick={() => setJustRestored(false)}>
                Dismiss
              </button>
            </p>
          )}
          <Itinerary itinerary={itinerary} onChange={handleItineraryChange} onReset={handleReset} />
        </>
      )}

      <footer className="app-footer">
        Built for the frontend internship assignment · itinerary generated by an LLM, reorder and remove freely
      </footer>
    </div>
  );
}
